const PAYMENT_STATUSES = Object.freeze({
  CREATED: 'CREATED',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMEOUT',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION'
});

module.exports = { PAYMENT_STATUSES };
